export enum EstadoOrdenCompra {
  BORRADOR = 'BORRADOR',
  APROBADA = 'APROBADA',
  ENVIADA_PROVEEDOR = 'ENVIADA_PROVEEDOR',
  RECIBIDA_PARCIAL = 'RECIBIDA_PARCIAL',
  RECIBIDA_TOTAL = 'RECIBIDA_TOTAL',
  CANCELADA = 'CANCELADA',
}
