export enum EstadoContratoAlquiler {
  BORRADOR = 'BORRADOR',
  RESERVADO = 'RESERVADO',
  PENDIENTE_ENTREGA = 'PENDIENTE_ENTREGA',
  ACTIVO = 'ACTIVO',
  EN_RETORNO = 'EN_RETORNO',
  CERRADO = 'CERRADO',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
}
