export enum EstadoComercialEquipo {
  DISPONIBLE = 'DISPONIBLE',
  VENDIDO = 'VENDIDO',
  ALQUILADO = 'ALQUILADO',
  RESERVADO = 'RESERVADO',
  EN_REPARACION = 'EN_REPARACION',
  USO_INTERNO = 'USO_INTERNO',
  BAJA = 'BAJA',
}
