export enum TipoCargoAlquiler {
  BASE = 'BASE',
  DEPOSITO_GARANTIA = 'DEPOSITO_GARANTIA',
  EXCEDENTE_COPIAS = 'EXCEDENTE_COPIAS',
  SOPORTE = 'SOPORTE',
  DANO = 'DANO',
  MORA = 'MORA',
  TRANSPORTE = 'TRANSPORTE',
  AJUSTE = 'AJUSTE',
}
