export enum TipoAfectacionIgv {
  GRAVADO_OPERACION_ONEROSA = 'GRAVADO_OPERACION_ONEROSA',
  EXONERADO_OPERACION_ONEROSA = 'EXONERADO_OPERACION_ONEROSA',
  INAFECTO_OPERACION_ONEROSA = 'INAFECTO_OPERACION_ONEROSA',
  EXPORTACION = 'EXPORTACION',
}
